# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class AddServiceStub(object):
  """service that handles requests and create responses
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/proto.AddService/Add',
        request_serializer=service__pb2.Request.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )
    self.Multiply = channel.unary_unary(
        '/proto.AddService/Multiply',
        request_serializer=service__pb2.Request.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )


class AddServiceServicer(object):
  """service that handles requests and create responses
  """

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Multiply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=service__pb2.Request.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
      'Multiply': grpc.unary_unary_rpc_method_handler(
          servicer.Multiply,
          request_deserializer=service__pb2.Request.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.AddService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
